# Generated by Django 4.2.24 on 2025-09-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default-avatar.png', upload_to='avatars/'),
        ),
    ]
