# Generated by Django 4.2.24 on 2025-10-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('default', 'Обычная'), ('important', 'Важная'), ('completed', 'Выполнена')], default='default', max_length=20, verbose_name='Статус'),
        ),
    ]
