# Generated by Django 4.2.24 on 2025-10-13 17:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planner', '0002_goal_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['-datetime'], 'verbose_name': 'Цель', 'verbose_name_plural': 'Цели'},
        ),
        migrations.AlterUniqueTogether(
            name='goal',
            unique_together={('user', 'title', 'datetime')},
        ),
    ]
